### ISSUE TITLE
generate responsive waveforms

### ISSUE THREAD

**Issue by jayenne** [Synchro/laravel-medialibrary-audio#5]
Hi, Is it possible to generate responsive waveform images at a range of sizes as with regular image uploads?
*although i am getting the image generated and it is in the medoa tabler as responvive, there is only 1 size and it doesn't render with the same tag I use for regular images `{{ $img('responsive')->attributes(['class'=>'img']) }}`

**Comment by Synchro** [comment]
That's not up to this plugin but [the conversions you define in MLP](https://spatie.be/docs/laravel-medialibrary/v9/converting-images/defining-conversions). In the case of an image it's the image itself, but obviously with audio there isn't anything, so that's what this plugin provides. In the system I'm using this in that works very nicely, but most of the scaling is done via CSS rather than multiple versions. You might need to do something with the [conversion generation](https://spatie.be/docs/laravel-medialibrary/v9/responsive-images/getting-started-with-responsive-images#generating-responsive-images-for-conversions) to produce resized images automatically.
