### ISSUE TITLE
missing mime-types / alternatives

### ISSUE THREAD

**Issue by jayenne** [Synchro/laravel-medialibrary-audio#8]
Ive noticed I'm not getting thumbs generated for audio/x-wav or audio/x-m4a mime-types and wondered if they needed adding to the supportedMimeTypes list?

**Comment by Synchro** [comment]
The problem here is that the MIME types that are supported are dependent on the underlying libraries, and also in browsers if you're looking to get MLP to play the media files. I don't have a definitive reference on what browsers support what formats. So while you could add the MIME types, there's no guarantee that they will work. There is also a lot of bad info around on what MIME types should be used. The official wav MIME type is `audio/vnd.wav`, defined in [RFC2361](https://datatracker.ietf.org/doc/html/rfc2361). I gather that `audio/x-wav` is a common wrong type caused by Apache not updating their list! Similarly, `audio/x-m4a` is not [an official type](https://datatracker.ietf.org/doc/html/rfc4337#page-3) for MPEG-4 audio, so I'd recommend investigating what's assigning those types to your files in the first place. Generally speaking, `x-anything` in a MIME type is only used for unofficial/unregistered types, just like for email and HTTP headers.
